name: "I have Issues"

description: "consume the output of the previous action and create a new issue in the repository"

inputs:
  joke:
    description: "This will become the body of the created issue"
    default: "a joke for you"
    required: true

runs:
  using: "node12"
  main: "index.js"
